api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "vip-price-transform"
type = "function"
uid = "bef797df-c5df-af60-636a-fe33af9ce226e1090b4d"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
